### ISSUE TITLE
KeyError: 'RAPID_API_KEY',UNSPLASH_API_KEY,GEMINI_API_KEY

### ISSUE THREAD

**Issue by adithya04dev** [PritK99/Social-Wizard#2]
### Issue
When attempting to access the environment variable 'RAPID_API_KEY' in the twitter.py module, a KeyError is raised.

### Proposed Changes
1. Include `python-dotenv` in the `requirements.txt` file.
2. Add the following lines at the beginning of twitter.py:
```python
from dotenv import load_dotenv
load_dotenv()

**Comment by PritK99** [comment]
You can set the API Keys using ```SET``` or ```EXPORT``` after creating virtual environment on Windows and Linux respectively.
